### ISSUE TITLE
A short comparison

### ISSUE THREAD

**Issue by ly29** [Sverchok/Sverchok#19]
![levels](https://cloud.githubusercontent.com/assets/6241382/22551238/46ea54c2-e954-11e6-935e-15c1fcdcfead.PNG)
In Sverchok Redux complexity is taken care for you. 
![skarmavbild 2017-02-02 kl 14 27 41](https://cloud.githubusercontent.com/assets/6241382/22551148/df35e53a-e953-11e6-8b7a-75e79b1942f9.png)
![skarmavbild 2017-02-02 kl 14 34 13](https://cloud.githubusercontent.com/assets/6241382/22551341/be205500-e954-11e6-9369-e72ec271e6c7.png)

Old Sverchok in comparison. By default only one of the circles get the 3rd level circles. In Redux this could be continued as long as desired, in the old we would have join lists and other things to make it work.

**Comment by ly29** [comment]
@enzyme69 
This means no more asking if a particular nodes is vectorized. Ever

**Comment by ly29** [comment]
![skarmavbild 2017-02-02 kl 14 38 30](https://cloud.githubusercontent.com/assets/6241382/22551515/542da688-e955-11e6-9fe1-2266239f7304.png)
In the old a list join would be necessary to achieve the same result.

**Comment by zeffii** [comment]
Let's do `v->m` soon and allow number/float as input to matrix in' s scale input

**Comment by ly29** [comment]
I agree, it is high on my priority list.
