### ISSUE TITLE
Basic Node set

### ISSUE THREAD

**Issue by ly29** [Sverchok/Sverchok#2]
The idea here is to provide a sufficient amount of nodes that system is usable and can be evaluated beyond totally technical details. A rough outline below based on templates from sverchok.

- [x]  Mesh out
- [x]  Object input
- [x]  Vector in
- [x]  Vectors Out
- [x]  linspace
- [x]  A range
- [x] Int/Float input
- [x]  Math
- [x]  Trigonometry
- [x]  Logic
- [x]  MatrixGenNode
- [x]  ListJoinNode
- [x]  List Split
- [x]  MaskListNode
- [x]  SvCircleNode
- [x]  ListLengthNode
- [x]  Random Node
- [x]  Topology creation, started.
- [x]  SvInterpolationNode
- [x]  VectorMathNode
- [x]  RandomVectorNode

**Comment by zeffii** [comment]
opportunity to now combine the Float node with the Int node.  "Value" node.

**Comment by ly29** [comment]
There will be color, string, vector etc. Also, we will see.

**Comment by ly29** [comment]
What I meant to say was, I will try to make a series of really minimal input nodes, if it is easy clean and discoverable how to switch between modes then let us do it.

**Comment by zeffii** [comment]
don't let me interfere :)

the nodes i'm most interested in are the viewers

**Comment by zeffii** [comment]
don't let me interfere :)

the nodes i'm most interested in are the viewers and the scripted node

**Comment by ly29** [comment]
The scripted nodes is fairly high on the todo the list since it will make development and testing much much easier.

For viewer a data tree viewer is for me higher priority than a open gl mesh viewer since it will make development easier.

**Comment by ly29** [comment]
The node code can become so small it is almost scary. Of course most nodes won't reduce to such a trivial degree but still.

```python
@node_func(bl_idname="SvRxTestAdd")
def add(x: Float = 0.0, y: Float = 0.0) -> Float:
    return x + y
```

**Comment by zeffii** [comment]
yeah but there's overhead for each function call, so without seeing speed tests i'm a tiny bit sceptical.

**Comment by zeffii** [comment]
unless it's something like
```python
@node_func(bl_idname="SvRxTestAdd")
def add(x: FloatList = [0.0], y: FloatList = [0.0]) -> FloatList:
    return [_x + _y for _x, _y in yield_zip_longest(x, y)]
```

**Comment by ly29** [comment]
I understand, but since I use numpy in the nodes which represents the inner loops I think it can be quite speedy

**Comment by ly29** [comment]
Still some way to before a meaningful comparison can be done...

**Comment by zeffii** [comment]
oh yeah , np  x+y works the same for 1*n arrays as for singular values

**Comment by ly29** [comment]
I will expand on it a bit but yeah, a ```Float``` is a ```np.array(dtype=np.float64)```

**Comment by ly29** [comment]
A slightly more realistic sample

```python
import numpy as np

from svrx.nodes.node_base import node_func
from svrx.typing import Float, Vertices


@node_func(bl_idname="SvRxNodeVectorIn")
def vector_in(x: Float = 0.0,
              y: Float = 0.0,
              z: Float = 0.0,
              w: Float = 1.0
              ) -> Vertices:
    """create vertices from inputs"""
    data = (x, y, z, w)
    counts = [len(x) for x in data]
    verts = np.empty((max(counts), 4))
    for i, count in zip(range(4), counts):
        verts[:count, i] = data[i]
        verts[count:, i] = data[i][-1]
    return verts

```

**Comment by portnov** [comment]
There is another one design possibility we should consider:
* The whole NodeTree corresponds to big structure, containing nodes; this structure is logically similar to AST used in programming languages compilers/interpreters.
* Each node does not execute loops by itself, but adds its function together with declaration about vectorizing schema and other meta-information into the NodeTree structure.
* There is global interpreter function, which walks through the full structure, executes loops and calls nodes fucntions.

This approach will not give a lot of features right now, but potentially, later we could add some optimizations into interpreter function, to speed things up. One obvious optimization is fusing of pack/unpack: for example, if node A internally works with lists, but outputs BMesh; and node B inputs BMesh, but internally works with lists; then we obviously can optimize things by omitting BMesh conversion entirely.
But this approach is obviously more complex, so we should think very carefully before applying it.

**Comment by ly29** [comment]
That is more less what happens right now, will soon outline how it works without having to dig into the code base.

The nodes aren't aware about when our why they are called, they are reduced to functions with some metadata generated from the function signature combined with the node tree.

**Comment by ly29** [comment]
![skarmavbild 2017-01-26 kl 13 15 05](https://cloud.githubusercontent.com/assets/6241382/22331052/9e9302cc-e3c9-11e6-98cb-6251be85288a.png)

The rudimentary system is working now. Still many limitations, but will focus on a small but powerful set of nodes. Then it is time to evaluate it a bit.

**Comment by ly29** [comment]
So this is taking a bit longer than expected, building systems is hard, but clear progress is being made.

**Comment by zeffii** [comment]
lets add a Float/Int node  .. it's going to wreck my head without it.

**Comment by ly29** [comment]
Okay I will get on it

**Comment by ly29** [comment]
![value](https://cloud.githubusercontent.com/assets/6241382/22429450/ef43adfe-e70a-11e6-9747-333c3baf3664.PNG)
Some value nodes

**Comment by ly29** [comment]
Next up would be some sort of topology creation, just line, plane and circle would go a long way...

**Comment by ly29** [comment]
![point](https://cloud.githubusercontent.com/assets/6241382/22432373/00898930-e715-11e6-84a4-2a5d8f1af7e4.PNG)
Or point input. Not totally happy. Might need some work if it is going to stay

**Comment by zeffii** [comment]
haha :)  cool

I think i'll pick off Object In , if you don't mind

**Comment by zeffii** [comment]
or at least get some of the code in

**Comment by ly29** [comment]
I don't mind, just do some cool flat storage for polygons

**Comment by ly29** [comment]
![topo](https://cloud.githubusercontent.com/assets/6241382/22466339/1de9a464-e7c0-11e6-87fb-c86055279db2.PNG)
Automatic topology node, line mode only

**Comment by ly29** [comment]
![mask](https://cloud.githubusercontent.com/assets/6241382/22466537/02f44046-e7c1-11e6-9fd0-87a91d95af6b.PNG)
Masking

**Comment by ly29** [comment]
![testing_objin](https://cloud.githubusercontent.com/assets/6241382/22469332/e70f5d6a-e7cb-11e6-8d62-d3c50c2fd70a.PNG)
Object input in the simplest way, had some crashes with it...

**Comment by ly29** [comment]
```python
from svrx.typing import Vertices, Edges, Object, Faces
from svrx.nodes.node_base import node_func
from svrx.util.smesh import SMesh

@node_func(bl_idname="SvRxObjectIn")
def object_in(obj : Object = None) -> (Vertices, Edges, Faces):
    if obj and obj.type == 'MESH':
        sm = SMesh.from_mesh(obj.data)
        return sm.as_pydata()
    else:
        return None, None, None
```

**Comment by ly29** [comment]
The tedious part about vector math is the 4x1 vectors but one should work with the 3x1 part for most of them

**Comment by zeffii** [comment]
yeah we can slice `:3` and `w` and recombine them after..

**Comment by zeffii** [comment]
(if the input is n*4..)

**Comment by ly29** [comment]
If you feel like go ahead, the input should be shape=(n, 4) in general, might have fix it here and there to ensure that however

**Comment by zeffii** [comment]
is w given a default 0.0 ?

**Comment by ly29** [comment]
For a point it should be 1 for a vector it should be 0.
So for cross, 0, for add, 1 if it is one for any, otherwise zero I guess

**Comment by zeffii** [comment]
also.. i recall writing numpy based topology node..
https://github.com/BlendCollider/FLOW/blob/master/nodes/uv/uv_edge_surf.py

**Comment by ly29** [comment]
@zeffii 
 Nice, will look at that later

**Comment by ly29** [comment]
You have also done some numpy random function for sverchok I seem to recall

**Comment by zeffii** [comment]
i'll dig through node scripts.

**Comment by ly29** [comment]
Ok so random is in but broken due to triggering another bug. boring

**Comment by ly29** [comment]
Earlier today I was thinking about how nice the adjust sockets code was that just seemed to work well and then of course it breaks for some reason. #hybris 
It has to redone in a somewhat more paranoid style

**Comment by ly29** [comment]
![topo2](https://cloud.githubusercontent.com/assets/6241382/22546364/16079fb6-e93d-11e6-9ab2-c682c114ee98.PNG)
Topology creation for line, circle, plane and cylinder. The code needs a reworking but simple enough for now.

**Comment by ly29** [comment]
![testing](https://cloud.githubusercontent.com/assets/6241382/22546716/7c1bf062-e93e-11e6-9b5f-817674f4ed33.PNG)
Now it is somewhat usable I think.

**Comment by ly29** [comment]
Enough that some simple speed tests might be resonable to do...

**Comment by ly29** [comment]
Now only vector math left. #12

**Comment by zeffii** [comment]
I'll make IntRange like 0.5.9  , Arange isn't really what i want.

**Comment by ly29** [comment]
Yeah I agree, it was only a quick thing to get started, both linspace and arrange should be replaced with nodes with similar modes to int range/float range

**Comment by zeffii** [comment]
also..you OK with making SN default color blue again?

**Comment by ly29** [comment]
Yes have a look at https://github.com/Sverchok/Sverchok/blob/master/nodes/classes.py#L181-L218

**Comment by ly29** [comment]
![interpol](https://cloud.githubusercontent.com/assets/6241382/22695769/2c5809be-ed4c-11e6-99b9-82c05770ae98.PNG)
Interpolation, 5 points above, 100 below

**Comment by zeffii** [comment]
@ly29  seen as values outside of the range 0.0 ... 1.0  produce weird results, perhaps allow the input of Integers to do something useful like  if T = 10, then internally produce a range `0..1/10 2/10...1.0 (inclusive)`

**Comment by ly29** [comment]
Like ```np.linspace(0.0, 1.0, count)```, yeah I am all for it. Will add it as a mode. even though we use ```.clip``` now

**Comment by ly29** [comment]
Doing that actually turns it into a generator, some code reuse below. Reusing the ```cubic_spline``` node for another mode.

```python

@node_func(bl_idname="SvRxVertexInterpol", multi_label="Interpolation", id=0)
def cubic_spline(verts: Vertices = Required,
                 t: Float = 0.5,
                 h: FloatP = 0.001,
                ) -> (Vertices, Vertices("Tanget")):
    spl = CubicSpline(verts[:,:3])
    points_out = np.ones((len(t), 4), dtype=np.float64)
    tangents_out = np.zeros((len(t), 4), dtype=np.float64)
    points_out[:, :3] = spl.eval(t)
    tangents_out[:, :3] = spl.tangent(t, h)
    return points_out, tangents_out

@vectorize
def int_cub_spline(verts, count, h):
    return cubic_spline(verts, np.linspace(0.0, 1.0, count), h)

@node_func(id=2)
def cubic_spline_count(verts: Vertices = Required,
                       count: Int = 10,
                       h: FloatP = 0.0001
                       ) -> ([Vertices], [Vertices("Tanget")]):
    return list(int_cub_spline([verts], count, [h]))
```

Yeah the type system needs some work. That and monads next.

**Comment by ly29** [comment]
Doing monads will answer a lot of questions I want to deal with.

**Comment by ly29** [comment]
Some gaps in modes but in place so closing.
