### ISSUE TITLE
Automatic type conversions

### ISSUE THREAD

**Issue by ly29** [Sverchok/Sverchok#20]
- From Vertices/Vector/Point to Matrix, gives a translation matrix per location ```Vertices -> [Matrix]```
- From Number to Vector, gives for each gives ```n``` gives ```(n, n, n, 0)``` . ```Number -> Vertices```
- From Matrix to Vertices, ```[Matrix] -> Vertices``` or ```Matrix -> Vertices```, not entirely sure about it
- From Number to Int, either by truncating or by round.
- From Object to Matrix/Vertices etc.
- Other

I don't want the number of conversion to be to big and want the rules to be clear and easy to understand, there as an help. For ambiguous situation is better to require clarity. So point out additional rules would be good or suggest a way for socket to show that it can handle multiple types. 

Want I don't want to happen is like the old Matrix In node where there is totally invisible functionality available in only one place that is impossible to predict from the UI. I would be better with some different modes for matrix in providing sensible variations.

**Comment by ly29** [comment]
For this to be implemented there will have to be some changes in the backend allowing a greater flexibility in internal representation, these changes were planed anyway to handle different execution types etc.

**Comment by ly29** [comment]
![v_to_m](https://cloud.githubusercontent.com/assets/6241382/22566522/81559f9e-e98c-11e6-933f-dc3f882513dc.PNG)
After some refactoring in now works by inserting a virtual node with virtual links into the execution.
The execution sequence here. Some heavy refactoring of functionality and location of things is still needed
```python
['Circle', 'VirtualNode<Create Matrix>', 'Mesh out']
```

**Comment by portnov** [comment]
Animation Nodes seem to use some magic: when you connect two sockets of different types, it automatically inserts a converter node between. Maybe we should think about similar approach?

**Comment by ly29** [comment]
The visible approach is also possible, for now I kept the node invisible. 
I am all for hearing arguments for and against.

**Comment by ly29** [comment]
Just for reference cycles does automatic type conversion in a seamless way.

**Comment by ly29** [comment]
Also something should be done in the system like automatic mesh conversions but other could be visible where connecting a socket would be like shortcut for create needed conversion nodes...

**Comment by ly29** [comment]
![auto_insert_node](https://cloud.githubusercontent.com/assets/6241382/22589227/8602c5e4-ea09-11e6-8da4-56bbfe740c86.gif)

Just to show that doing it the other way would **not** be so difficult, adding code to do either would be easy as well. Of course insertion point etc could be tweaked.
https://github.com/Sverchok/Sverchok/tree/real_nodes_insert

**Comment by zeffii** [comment]
not sure if possible with an operator, but `shift`+`ctrl`+`drag` + `connect` could spawn the suggested node inbetween?

**Comment by ly29** [comment]
Not sure either, will code for both possibilities for now.

**Comment by ly29** [comment]
Merged.

**Comment by enzyme69** [comment]
![screen shot 2017-02-05 at 13 17 50](https://cloud.githubusercontent.com/assets/3952687/22623206/845b8508-eba5-11e6-9444-8c2ae3fdb507.png)

Vector > Matrix is now automatic. But at what point, we have this conversion node.

**Comment by ly29** [comment]
That is for redux only most likely. Which is usable but still lacking many features/nodes.

**Comment by ly29** [comment]
![scale](https://cloud.githubusercontent.com/assets/6241382/22778506/814af834-eeb7-11e6-8b05-ab8c13b3e52b.PNG)
So this also works. The float value n is applied as (n, n , n)

**Comment by ly29** [comment]
Going with implicit conversion for now.
