### ISSUE TITLE
Primitives and Other generators

### ISSUE THREAD

**Issue by zeffii** [Sverchok/Sverchok#22]
currenty the  < 0.6 sverchok has a moderately large list of mesh generators, but they aren't organized as tidy as they could be. 

I wonder might we do a similar separate menu like Object Add  for primitives, with a similar categorization. (the notable exception would be the Nurbs..which are not exposed very well in bpy)

**Comment by ly29** [comment]
Organized is a keyword. The default could be very similar but allowing different advanced options like strange options like plane does.

**Comment by ly29** [comment]
As discussed in other places the *generator* pattern for functions was slightly awkward and not entirely logical leaving us with two choice, either amend the type system or redo the decorator allowing it to be used directly

```python
import bmesh
from svrx.util.geom import vectorize
from svrx.util.mesh import rxdata_from_bm

@vectorize
def make_icosphere(subdiv, diam):
    bm = bmesh.new()
    bmesh.ops.create_icosphere(bm, subdivisions=subdiv, diameter=diam, calc_uvs=False)
    return rxdata_from_bm(bm)

@node_script
def sn_icosphere(subdiv: Int = 2, diam: Float = 1.0) -> ([Vertices], [Edges], [Faces]):
    return list(make_icosphere(min(subdiv, 5), diam))  
```

Rethinking that a little bit made me come up with the following which auto wraps inputs allowing the functions to be tested in the blender python console. It also allows variable matching, the fact that the decorated function is exposed directly to the system allows further settings, like variable match type to be, potentially, controllable from the system.

```python
import bmesh
from svrx.util.geom import generator
from svrx.util.mesh import rxdata_from_bm

@node_script
@generator
def sn_icosphere(subdiv: Int(min=0, max=5) = 3, diam: Float = 1.0) -> ([Vertices], [Edges], [Faces]):
    bm = bmesh.new()
    bmesh.ops.create_icosphere(bm, subdivisions=min(subdiv, 5), diameter=diam, calc_uvs=False)
    return rxdata_from_bm(bm)
```

Todo:

- [x] Allow only certain parameters to be wrapped
- [x] Provide match function override at run time

**Comment by ly29** [comment]
The ```@generator``` should probably not be in ```util.geom``` but in ```util.function```

**Comment by zeffii** [comment]
or `util.decorators`

**Comment by zeffii** [comment]
maybe move the `util.geom` to `libs.geom` if it's content is only mesh producing functions ( that was the original intent of `sverchok.utils.geom` ) it seems to have slightly morphed.

**Comment by ly29** [comment]
Yeah a lib for core functions makes sense. ```circle``` is a ```util```, mesh etc is a core functionality

**Comment by ly29** [comment]
Actually should probably do both a name review and project layout review. 

```
nodes.classes -> nodes.classes.files
from nodes.node_base import node_func -> from nodes import node_func
etc.
```
Ensure consistent node namning, like
```
SvRxNode{Module}{Name}
SvRxNodeNumberMath
```

**Comment by zeffii** [comment]
i'll find somethign else to do... but it won't be until later today at the earliest : /

**Comment by ly29** [comment]
I won't have time for that today either, need to do some other stuff.

**Comment by ly29** [comment]
Updated all nodes from vectorize to generator and also the cookbook.

**Comment by ly29** [comment]
The best generator function

```python
@node_func(bl_idname='SvRxNodeBmeshGenerate', multi_label="Bmesh Gen", id=0)
def create_monkey() -> BMesh:
    bm = bmesh.new()
    bmesh.ops.create_monkey(bm)
    return bm
```

**Comment by zeffii** [comment]
i'll make a `cricket` :)

**Comment by ly29** [comment]
That is a slightly bigger challenges :)

**Comment by zeffii** [comment]
![](https://cloud.githubusercontent.com/assets/619340/8018490/cdf0d6cc-0c1e-11e5-98d2-30fa03de70ed.png)

https://www.dropbox.com/s/pe7f6ciza8vt8fq/cricket_remakeFIXR.blend?dl=0

**Comment by ly29** [comment]
Yeah that is nice. 👍

**Comment by zeffii** [comment]
hmmm.. it's a little geometry heavy.

**Comment by ly29** [comment]
Suzanne is also of limited use inside of the system but since it is basically free to add it I went there.

Still cannot get over how small the nodes have become. Almost all the fluff is gone, dealing with input, checking for outputs etc, parsing lists.

**Comment by zeffii** [comment]
**edited**

```python
import os

from svrx.util.mesh import rxdata_from_pydata

def simple_obj_loader(path):
    verts, edges, faces = [], [] ,[]
    add_vert = verts.append
    add_face = faces.append
    with open(path) as ofile:
        for line in ofile:
            if line.startswith('v'):
                add_vert([float(i) for i in line[2:].strip().split(' ')])
            if line.startswith('f'):
                add_face([int(i)-1 for i in line[2:].strip().split(' ')])
    
    return verts, edges, faces


@node_script
def sn_make_cricket() -> (Vertices, Edges, Faces):
    mesh_objects_path = r"C:\Users\zeffi\Desktop\GITHUB\DEEP\svrx\util\mesh_objects"
    obj_path = os.path.join(mesh_objects_path, "cricket.obj")
    verts, _, faces = simple_obj_loader(obj_path)
    return rxdata_from_pydata(verts, faces=faces)

```
haha

![image](https://cloud.githubusercontent.com/assets/619340/22802826/a91c8700-ef12-11e6-8373-f499280cd007.png)

https://github.com/Sverchok/Sverchok/pull/38

**Comment by ly29** [comment]
Function signature should be like below.

```python

@node_script
def sn_make_cricket() -> (Vertices, Edges, Faces):
```

**Comment by zeffii** [comment]
cool, that's clearer now

**Comment by nortikin** [comment]
why obj file?

**Comment by ly29** [comment]
simple standard format text format, easy to work with

**Comment by nortikin** [comment]
ok, lets use it. than inner svrx.obj.library

**Comment by zeffii** [comment]
ok, that should look like this now:
```python
from svrx.util.mesh import rxdata_from_pydata
from svrx.util.importers import named_mesh_path, obj_to_pydata_lite

@node_script
def sn_make_cricket() -> (Vertices, Edges, Faces):
    obj_path = named_mesh_path("cricket.obj")       #  returns the library path +  object name
    verts, _, faces = obj_to_pydata_lite(obj_path)  #  accepts full valid path
    return rxdata_from_pydata(verts, faces=faces)
```

**Comment by zeffii** [comment]
i like the idea of storing these as zipped files, .. but Google lately made a geometry compressor worth investigating :)

**Comment by ly29** [comment]
I am partial towards ```.gz``` file but ```.zip``` probably makes more sense.
https://docs.python.org/3/library/archiving.html

**Comment by zeffii** [comment]
https://opensource.googleblog.com/2017/01/introducing-draco-compression-for-3d.html

**Comment by ly29** [comment]
Would be good to have that as export/import from blender if there isn't a plugin yet as well

**Comment by ly29** [comment]
Stupid performance test, sticking a lru cache on it.

```python
def test():
    import time
    obj_path = named_mesh_path("cricket.obj")
    start = time.perf_counter()
    obj_to_pydata_lite(obj_path)
    stop = time.perf_counter()
    print(stop-start)
    start = time.perf_counter()
    obj_to_pydata_lite(obj_path)
    stop = time.perf_counter()
    print(stop-start)
    start = time.perf_counter()
    obj_to_pydata_lite.__wrapped__(obj_path)
    stop = time.perf_counter()
    print(stop-start)
```


```
>>> svrx.util.importers.test()
0.014265173333313896 # first access to cache, cache miss, loading object
2.1333333393158682e-06 # second access
0.013622613333325262 # direct access using __wrapped__
```

**Comment by ly29** [comment]
```python
@functools.lru_cache(maxsize=16)
def obj_to_pydata_lite(path)
....
```

**Comment by zeffii** [comment]
that's a 5 magnitude smaller. ?

**Comment by zeffii** [comment]
almost 7k times faster?..wtf..?

**Comment by ly29** [comment]
Yes, it turns the function into a dictionary lookup basically.
```python
>>> svrx.util.importers.test()
1.49E-02 # cache miss and load
1.71E-06 # cached
1.34E-02 # raw access
```

**Comment by ly29** [comment]
Something like this happens:
```python

def func(path):
    if path in _cache:
        return _cache[path]
    else:
        res = inner_func(path)
        _cachep[path] = res
        return res
```

**Comment by ly29** [comment]
https://docs.python.org/3.5/library/functools.html

**Comment by zeffii** [comment]
i might have to read that.

**Comment by ly29** [comment]
It might be annoying if one changes the geometry, should put a note in there about how to work around in the docstring

**Comment by zeffii** [comment]
maybe offer `cached_basic_obj_to_pydata` and `basic_obj_to_pydata`

**Comment by ly29** [comment]
The other way around, long name for the uncommon case, ```uncached_basic_obj_to_pydata``` and ```basic_obj_to_pydata```.

```python
def uncached_obj_to_pydata_lite(path):
    return obj_to_pydata_lite.__wrapped__(path)
```

**Comment by zeffii** [comment]
OK.  :)

**Comment by ly29** [comment]
It has kind on moved on into other issues
