### ISSUE TITLE
Monad of Totem

### ISSUE THREAD

**Issue by enzyme69** [Sverchok/Sverchok#29]
[array_inside_sverchok_004_2017_02_06_11_19.zip](https://github.com/Sverchok/Sverchok/files/754428/array_inside_sverchok_004_2017_02_06_11_19.zip)

I am making this node setup that generates like a TOTEM of Array. Each part of totem can be replaced randomly.

I made a MONAD out of it and trying to vectorize. But seems to fail. Wondering why...

Is this such a case where MONAD vectorize was not made for it.

**Comment by zeffii** [comment]
this is the wrong repo to ask about monads @enzyme69 . Not implemented yet here.

**Comment by ly29** [comment]
Please make an issue over at usual place. Will get back to you about it.
