### ISSUE TITLE
Mesh - rxdata_from_pydata

### ISSUE THREAD

**Issue by zeffii** [Sverchok/Sverchok#33]
There will be times we might this kind of conversion instead of writing something as np immediately, just to get something working quickly, some esoteric generator.

https://github.com/Sverchok/Sverchok/blob/master/util/smesh.py  

i'd like to get stuck into the `SMesh.from_pydata` and `SVertices.from_pydata` ,

**Comment by ly29** [comment]
Absolutely needed.

**Comment by zeffii** [comment]
almost..
```python
from sverchok.nodes.generator.sphere import sphere_verts, sphere_edges, sphere_faces
from svrx.util.geom import vectorize
from svrx.util.mesh import rxdata_from_pydata

@vectorize
def make_sphere(U, V, Radius):
    v = sphere_verts(U, V, Radius, False)
    e = sphere_edges(U, V)
    f = sphere_faces(U, V)
    return rxdata_from_pydata(v, e, f)

@node_script
def sn_sphere(U: Int = 12, V: Int = 10, Radius: Float = 1.0) -> ([Vertices], [Edges], [Faces]):
    return list(make_sphere(U, V, Radius))

```

**Comment by ly29** [comment]
I really need to sort out the generator pattern. 

Otherwise I will have a check at it tomorrow.

**Comment by ly29** [comment]
For sn it works quite well to import from Sverchok, nice touch :)

**Comment by zeffii** [comment]
I keep getting called away.. can barely finish thoughts :/  but it seems SN is showing Int / Float as property names instead of U..V..Radius.. now?

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/22754560/31f6ea76-ee40-11e6-88dc-1978199eb886.png)

**Comment by ly29** [comment]
Most have messed up then. Will take look at that.

**Comment by zeffii** [comment]
edges (even though they would be skipped with this example's full polygon count) gives an error
```
  File "svrx\util\mesh.py", line 47, in bmesh_from_pydata
    if not edges is None and len(edges):
TypeError: object of type 'SvEdges' has no len()
```
does `SvEdges` need a `def __len__`  or what

**Comment by ly29** [comment]
Ok I see what I did, not to clever.

**Comment by ly29** [comment]
Yes for that to work, that len check feels a bit redundant

**Comment by zeffii** [comment]
agreed

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/22755578/0d9507b8-ee44-11e6-8fe8-d0ba9ef4f88a.png)

**Comment by ly29** [comment]
Fixed the name issue in master

**Comment by zeffii** [comment]
a ha!
```python
def rxdata_from_pydata(verts, edges=None, faces=None):
    # v = SvVertices.from_pydata(verts)
    # e = SvEdges.from_pydata(edges)
    # f = SvPolygon.from_pydata(faces)
    # return v, e, f
    rxm = SMesh.from_pydata(verts, edges, faces)
    return rxm.vertices, rxm.edges, rxm.faces
```

**Comment by zeffii** [comment]
how about `SMesh.from_pydata(verts, edges, faces).as_rxdata`

**Comment by zeffii** [comment]
seems to work :)  but i'm sure i've not dealt well with the scenario of empty lists...

**Comment by ly29** [comment]
The empty scenario is a tricky scenario...
A property makes sense since it is basically not any heavy computed data but free.

**Comment by zeffii** [comment]
```python
from sverchok.nodes.generator.torus import torus_verts, torus_edges, torus_polygons

from svrx.util.geom import vectorize
from svrx.util.smesh import SMesh

@vectorize
def make_torus(R, r, N1, N2, rPhase, sPhase):
    v = torus_verts(R, r, N1, N2, rPhase, sPhase, False)[0]
    e = torus_edges(N1, N2)
    f = torus_polygons(N1, N2)
    return SMesh.from_pydata(v, e, f).as_rxdata

@node_script
def sn_torus(
    R: Float = 2.0, r: Float = 0.6, 
    N1: Int = 22, N2: Int = 15, 
    rPhase: Float = 0.0,
    sPhase: Float = 0.0) -> ([Vertices], [Edges], [Faces]):
    return list(make_torus(R, r, N1, N2, rPhase, sPhase))
```
hahaha :)

**Comment by zeffii** [comment]
we need to be strict with Generators that land in SvRx. They must be numpy only. else it's a scriptnode.

**Comment by zeffii** [comment]
or we give them a prefix to the bl_idname/label ..

**Comment by ly29** [comment]
Initially we should be strict with everything while we test out what works and what doesn't. 
Tomorrow I will tackle the generator pattern, it feels like a clean solution could be done quite easily.

**Comment by zeffii** [comment]
(had copy paste mistake in above snippet)

![image](https://cloud.githubusercontent.com/assets/619340/22757013/7e688528-ee49-11e6-8383-fc58db6a5341.png)

**Comment by zeffii** [comment]
OK. that's enough for now. let me know if you want to merge the PR. https://github.com/Sverchok/Sverchok/pull/34

**Comment by ly29** [comment]
Done

**Comment by ly29** [comment]
I really miss the opengl viewer, thinking about a quick hack to port it.
Or even just abusing the sverchok built in one via import for now...

**Comment by zeffii** [comment]
..and indexviewer... but as it was originally made .. not with the extra baking, placing screen text on verts/edges/faces should be its own node.

**Comment by nortikin** [comment]
@zeffii @ly29 
openGL viewer need to be different, + 2.8 blender will be with other BGL
Maybe to include in new version osl or something. shading+lighting in bgl, as i wanted long ago.
PS
where is 2.8 BGL to see?

**Comment by ly29** [comment]
@nortikin 
For 2.8 yes, but it will be some time before that happens. For 2.78b where we are now and 2.79 bgl will still be there.
