### ISSUE TITLE
BMesh nodes

### ISSUE THREAD

**Issue by ly29** [Sverchok/Sverchok#35]
![bmesh_nodes](https://cloud.githubusercontent.com/assets/6241382/22785596/359f6118-eed5-11e6-870d-f3c22e03f398.PNG)
To play around bit I did this.

A typical node ends up looking something like this.

```python
@node_func(id=1)
@generator(mask=(1, 0))
def solidify(bm: BMesh = Required, thickness: Float = 1.0) -> [BMesh]:
    bm = bm.copy()
    geom_in = bm.verts[:] + bm.edges[:] + bm.faces[:]
    bmesh.ops.solidify(bm, geom_in=geom_in, thickness=thickness)
    return bm
```
Just the ```sv_init``` function is longer.
https://github.com/nortikin/sverchok/blob/master/nodes/modifier_make/solidify.py

**Comment by ly29** [comment]
Of course bmesh directly to mesh out is also coming soonish.

**Comment by ly29** [comment]
![bmesh_nodes2](https://cloud.githubusercontent.com/assets/6241382/22788200/4175f862-eedf-11e6-976b-47759cf07a24.PNG)

**Comment by ly29** [comment]
Great oppoturnity to add some bmesh nodes if ones is so inclined.
https://docs.blender.org/api/blender_python_api_2_78_release/bmesh.ops.html#module-bmesh.ops

**Comment by portnov** [comment]
@generator(mask=(1, 0))
what the magic mask? :)

**Comment by ly29** [comment]
@portnov 
Short version, to avoid the whole ```s = scale[0]``` problem the ```@generator``` decorator matches up all the incoming arguments that are lists. 
However a ```bmesh``` object is already atomic and can't really be divided into any meaningful to it tells the generator decorator which objects to match. Not totally happy with naming here.

For for example. ```soldify(bm, [0.1, .5, .9])``` will result in ```solidify``` being called three times producing the different thicknesses. The input bmesh is the same.

```
solidfy(bm, 0.1)
solidfy(bm, 0.5)
solidfy(bm, 0.9)
# the result will be collected into a list an put into the data tree.
soldify(bm, [0.1, .5, .9]) -> [bm0, bm1, bm2]
```

**Comment by portnov** [comment]
Maybe better encode this information into argument types? smth like

`def solidify(bm: BMesh = Required(iterate=False), thickness: Float(iterate=True) = 1.0) -> [BMesh]:`

(default value of this new type parameter should be true I think)

?

**Comment by ly29** [comment]
Yes that is also a sane option. 
I should be true except for parameterns where it doesn't make sense like bmesh.

**Comment by ly29** [comment]
Extending slightly so that the default of things that cannot be iterated is False making for very sane defaults. Right I think one node needs these options with these defaults...

**Comment by ly29** [comment]
So the generator now inspect the type of the function and generates an mask, by using sensible defaults there is only one place where it has been needed to specify it. One on hand that is almost to hidden to be useful, on the other it is nice that it just works.
 
```python
@node_func(id=2)
@generator
def cubic_spline_count(verts: Vertices(iterable=False) = Required,
                       count: Int = 10,
                       h: FloatP = 0.0001
                       ) -> ([Vertices], [Vertices("Tanget")]):
    return cubic_spline(verts, np.linspace(0.0, 1.0, count), h)
```

**Comment by ly29** [comment]
In hold for now...
