### ISSUE TITLE
mesh names

### ISSUE THREAD

**Issue by zeffii** [Sverchok/Sverchok#4]
let's go ` name + str("%04d" % idx)  `   padding to 4 numbers
and
```python
    obj['idx'] = idx
    obj['basename'] = node.basemesh_name
```
that solves all the tricky finding/removing stuff.

**Comment by ly29** [comment]
That does sound very resonable. The whole mesh out certainly needs a big overhaul it is thrown together with some small edits. Partly to test out stateful nodes as discussed earlier.

**Comment by ly29** [comment]
Changed as suggested

**Comment by zeffii** [comment]
rather..   `name + '.' + str("%04d" % idx)`   #  some_name.0000

**Comment by zeffii** [comment]
the default mesh function isn't needed, see
https://github.com/nortikin/sverchok/blob/master/nodes/viz/viewer_skin_mk1.py#L84-L111

**Comment by ly29** [comment]
Will continue to change that, old code I copied over from previous redux to get something going quickly.

**Comment by ly29** [comment]
If you want to change that feel welcome to go for it :)

**Comment by zeffii** [comment]
OK/ expect incoming mesh output  :)

**Comment by ly29** [comment]
Made a Mesh socket and type

**Comment by zeffii** [comment]
i presume it will take bm and some other concoction :)

**Comment by ly29** [comment]
The types only changes the socket type right now, no more, no less.

Also would probably be a good idea to make a copy of the mesh coming into to the node.

```python
@node_func(...)
def mesh_out(bm: Mesh = Required):
    bm = bm.copy()
```

**Comment by ly29** [comment]
Also as hint, the node functions work in the python console.

**Comment by zeffii** [comment]
i'll continue this in the PR https://github.com/Sverchok/Sverchok/pull/5
