### ISSUE TITLE
API to simplify mesh creation

### ISSUE THREAD

**Issue by portnov** [Sverchok/Sverchok#40]
In many cases when we want to generate some geometry, it's relatively easy to calculate vertex coordinates; but if there is a lot of vertices, then it's hard to figure out which vertex we need to connect to which. And this part of code can be most unintuitive.

What we can have in zero step is smth like

```
class VertexHandle(object):
  def __init__(self, index, name=None):
    self.index = index
    self.name = name

class Mesh(object):
  def add_vertex(self, vertex, name=None) -> VertexHandle:
  ...

  def add_edge(self, VertexHandle, VertexHandle):
  ...

  def add_face(self, *VertexHandle):
  ...

  def to_rxdata(self):
  ...

  def to_bmesh(self):
  ...
```

so that we could write smth like

```
mesh = Mesh()
a = mesh.add_vertex((1.0, 2.0, 3.0))
b = mesh.add_vertex((2.0, 2.0, 3.0))
c = mesh.add_vertex((3.0, 2.0, 3.0))
mesh.add_face(a,b,c)
...
return mesh.to_rxdata()
```

**Comment by zeffii** [comment]
then how about also adding 
`mesh.add_vertices(vert_list, make_face=True)`

**Comment by ly29** [comment]
Bmesh does something similar but an api like that does make sense to have

```python
>>> import bmesh
>>> bm=bmesh.new()
>>> a=bm.verts.new((0,0,0))
>>> b=bm.verts.new((0,1,0))
>>> c=bm.verts.new((1,1,0))
>>> d=bm.verts.new((1,0,0))
>>> bm.faces.new((a,b,c,d))
<BMFace(0x10da66a10), index=-1, totverts=4>
```

**Comment by ly29** [comment]
Until somebody steps up and does it I think bmesh does enough of this.
