### ISSUE TITLE
The great namning debacle

### ISSUE THREAD

**Issue by ly29** [Sverchok/Sverchok#41]
Looking into ```svrx.typing``` one quickly sees reason for concern. Many of the names are pretty generic and clashes with blender ````mathutils```. Names in particular that need replacement.

- Matrix
- Vector
- Color

Doing that starting out decided to just pick natural names and it mostly worked out. But some suggestions for avoid doing things like below.

```python
import mathutils as mu
mat = mu.Matrix()
# or even worse
import svrx.typing as t
@node_func
def transform(vert: t.Vertices = None, mat: t.Matrix) -> t.Vertices:
```

**Comment by zeffii** [comment]
like in OpenGL

- vec2
- vec3
- vec4
- color3
- color4

**Comment by ly29** [comment]
There is a certain undeniable practicality to that.

The Base type for all the vectors type is called ```Number4f``` partly inspired by OpenGL like thinking. This type is only used internally and isn't matched to any socket type.

**Comment by zeffii** [comment]
it's mostly about Vector and Matrix?

**Comment by ly29** [comment]
Yeah

**Comment by zeffii** [comment]
Mat44 Mat33 Vec3List..

**Comment by zeffii** [comment]
aside from those being rather ugly, it's close to some shader languages i believe

**Comment by ly29** [comment]
Hmm, I will think a bit about it.

**Comment by zeffii** [comment]
rxMatrix

**Comment by zeffii** [comment]
or hint that people should do `from mathutils import Matrix as bMatrix`

**Comment by zeffii** [comment]
mostly likely we won't be using Matrix from mathutils at all.. or definitely not nearly as often as 0.59 (which needs a codename at this point..)

**Comment by zeffii** [comment]
i'm happy to call Sverchok 0.5.9  " N1 "   iteration 1

**Comment by ly29** [comment]
I was also thinking that you wouldn't have to use ```mathutils.Vector``` or ```mathutils.Matrix``` as much but the bmesh api uses and exposes them a lot. 

The easiest is something like slapping a prefix on all types, like rx as suggested.

The 0.5.9 will forever be reaching towards 0.6 but never quite getting there... :)

**Comment by ly29** [comment]
I won't do the renaming for a day or two anyway so there is time to consider it enough not have to do it again.

**Comment by ly29** [comment]
By this time next week I would like to have a basically usable system.

**Comment by zeffii** [comment]
> but the bmesh api uses and exposes them a lot.

like return values from function... i'd still go for naming the return values bVector and bMatrix

**Comment by zeffii** [comment]
only because out main math _system_ won't be mathutils.. really.

**Comment by ly29** [comment]
that is certainly true, but still living inside blender context it is better to not clash with common names there.

**Comment by ly29** [comment]
Will resolve this tomorrow.
