### ISSUE TITLE
Texture script node

### ISSUE THREAD

**Issue by ly29** [Sverchok/Sverchok#56]
![script_texture](https://cloud.githubusercontent.com/assets/6241382/23130496/f162fee6-f786-11e6-960b-a2746add9c23.PNG)

Inspired by https://github.com/nortikin/sverchok/issues/1248
```python

import numpy as np
import bpy
from svrx.util.function import array_as

def assign_image(image, size ,buffer):
    np_buff = np.empty(len(image.pixels), dtype=np.float32)
    np_buff.shape = (-1, 4)
    np_buff[:,:] = buffer[:,np.newaxis]
    np_buff[:,3] = 1
    np_buff.shape = -1
    image.pixels[:] = np_buff
    return image

@node_script
def texture(value: Float = 0.5,
            size: Int = 64,
            name: String = "texture"):
    image = bpy.data.images.get(name)
    if not image:
        image = bpy.data.images.new(name, size, size, alpha=False)
        image.pack
    else:
        image.scale(size, size)
    new = array_as(value, (size*size,))
    assign_image(image, size, new)
    image.update_tag()                    
                    
                    

```

**Comment by ly29** [comment]
String socket type isn't working yet for some strange reason... working on it Done.

**Comment by ly29** [comment]
Of course this way is slower than an opengl viewer but still soo much faster than the old Sverchok.
1024 image in 0.5s, 512 in about .1s

**Comment by ly29** [comment]
Feels kind of silly how easy this was, never though about before... @kalwalt idea is really nice, and Redux makes much more practical speedwise

**Comment by ly29** [comment]
![texture_update](https://cloud.githubusercontent.com/assets/6241382/23131501/7bb6d088-f78a-11e6-880a-5583ebe77551.gif)
@enzyme69 
This looks nice now?

**Comment by ly29** [comment]
@zeffii 
Now it would be nice with some noise

**Comment by zeffii** [comment]
yeah! let's see if the numpy modules has 3d noise.. else expect bottlenecking.

**Comment by zeffii** [comment]
procedural textures can be a fantastic way to make geometry seem much more complex, by passing bump-maps...  / alpha maps
![image](https://cloud.githubusercontent.com/assets/619340/23133705/51ff8d4a-f792-11e6-87fb-8783fda9d050.png)

**Comment by portnov** [comment]
An idea about generating textures from Sverchok is.. well, interesting, but not much, since Blender already has its own texture nodes. What is more promising is integration of Sverchok with texture (or even material) nodes (see AN also). For example, we can have "Texture output" Sverchok node and "Sverchok input" texture node, to pass data from sverchok to textures for further processing; or vice versa, "texture input" and "sverchok output"...

**Comment by portnov** [comment]
@zeffii 
I dont think it is possible to make holes in mesh by using bumpmaps... or is it?

**Comment by zeffii** [comment]
alpha maps.

**Comment by ly29** [comment]
The difference is that here you could plug in your on code easily, but no it isn't the main purpose.
But since it is a new application for sverchok I find it fun.

**Comment by ly29** [comment]
Obviously you can use OSL so the application isn't that big but anyway.

**Comment by ly29** [comment]
Game of life.
![gameoflife](https://cloud.githubusercontent.com/assets/6241382/23134354/cf764ec4-f794-11e6-9292-62295ae08e3e.gif)

Based on http://www.labri.fr/perso/nrougier/teaching/numpy/numpy.html

```python

import bpy
import numpy as np

@node_script
def get_board(name: String = "") -> Int("board"):
    images = bpy.data.images[name]
    in_board = np.array(images.pixels[:])
    in_board.shape = (-1, 4)
    board = np.zeros((len(in_board),), dtype=np.int32)
    board[:] = in_board[:,0].round().astype(np.int32)
    return board
```

```python
# Copyright INRIA
# Contributors: Nicolas P. Rougier (Nicolas.Rougier@inria.fr)
#
# DANA is a computing framework for the simulation of distributed,
# asynchronous, numerical and adaptive models.
#
# This software is governed by the CeCILL license under French law and abiding
# by the rules of distribution of free software. You can use, modify and/ or
# redistribute the software under the terms of the CeCILL license as circulated
# by CEA, CNRS and INRIA at the following URL
# http://www.cecill.info/index.en.html.
#
# As a counterpart to the access to the source code and rights to copy, modify
# and redistribute granted by the license, users are provided only with a
# limited warranty and the software's author, the holder of the economic
# rights, and the successive licensors have only limited liability.
#
# In this respect, the user's attention is drawn to the risks associated with
# loading, using, modifying and/or developing or reproducing the software by
# the user in light of its specific status of free software, that may mean that
# it is complicated to manipulate, and that also therefore means that it is
# reserved for developers and experienced professionals having in-depth
# computer knowledge. Users are therefore encouraged to load and test the
# software's suitability as regards their requirements in conditions enabling
# the security of their systems and/or data to be ensured and, more generally,
# to use and operate it in the same conditions as regards security.
#
# The fact that you are presently reading this means that you have had
# knowledge of the CeCILL license and that you accept its terms.
# -----------------------------------------------------------------------------

import numpy as np

def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z


@node_script
def game_of_life(board: Int = 0, size: Int = 512)-> Int("board"):
    board.shape = (size,size)
    out = iterate(board.copy())
    out.shape = -1
    return out
```

**Comment by ly29** [comment]
So then we are turing complete using the image buffer. Nice.

**Comment by zeffii** [comment]
need frame input. with controls on the node 

```
------------------------------------------------
|                                 current frame|
|                                   start frame|
|                                     end frame|
|                                              | 
|  >> |> || <| << [frame number] [start, stop] |
-----------------------------------------------   
```

**Comment by zeffii** [comment]
maybe even optionally draw a timelime

**Comment by ly29** [comment]
And a animation handler.

**Comment by ly29** [comment]
The animation handler is now in but is stupid. Will educate it a bit tomorrow.
![gameoflife2](https://cloud.githubusercontent.com/assets/6241382/23135562/7531b246-f799-11e6-96a7-b135e42b740a.gif)

**Comment by ly29** [comment]
Anyway there is potential here but for now just playing with these scripts.

**Comment by kalwalt** [comment]
@ly29 i want to try your script for outputting in the image editor:

````python
import numpy as np
import bpy
from svrx.util.function import array_as

def assign_image(image, size ,buffer):
    np_buff = np.empty(len(image.pixels), dtype=np.float32)
    np_buff.shape = (-1, 4)
    np_buff[:,:] = buffer[:,np.newaxis]
    np_buff[:,3] = 1
    np_buff.shape = -1
    image.pixels[:] = np_buff
    return image

@node_script
def texture(value: Float = 0.5,
            size: Int = 64,
            name: String = "texture"):
    image = bpy.data.images.get(name)
    if not image:
        image = bpy.data.images.new(name, size, size, alpha=False)
    
    new = array_as(value, (size*size,))
    assign_image(image, size, new)
    image.update_tag()
````

does it is complete?  i have no sockets with this.

**Comment by zeffii** [comment]
@kalwalt  it should be outputting directly to Image Editor :)

**Comment by zeffii** [comment]
(and you can't use 'Text' as the textblock's name : )

**Comment by kalwalt** [comment]
in the editorr i have set the size to  64 and name=texture , maybe need to restart blender.

> (and you can't use 'Text' as the textblock's name : )

this is the issue!

**Comment by zeffii** [comment]
it's my idea to 'disallow' the name Text for textblocks.  We should perhaps add a small notification if you try to load a text with that name..

**Comment by ly29** [comment]
I would update it like this then it will handle changing size
```python
@node_script
def texture(value: Float = 0.5,
            size: Int = 64,
            name: String = "texture"):
    image = bpy.data.images.get(name)
    if not image:
        image = bpy.data.images.new(name, size, size, alpha=False)
    else:
        image.scale(size, size)
    new = array_as(value, (size*size,))
    assign_image(image, size, new)
    image.update_tag()
```

**Comment by zeffii** [comment]
also `script` and `script.py` are not a good idea.  This way we force some level of descriptiveness

**Comment by ly29** [comment]
@kalwalt 
You are probably the third person to use this redux, please ask about anything you find strange or buggy

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/23330042/ffdc2c10-fb44-11e6-9a31-5fe583fd2ca9.png)

**Comment by zeffii** [comment]
```diff
- Random Int | RandInt | Random Float 
+ Int | RandInt | Float 
```
@ly29 maybe those labels are a little long

**Comment by kalwalt** [comment]
@ly29 @zeffii i can't load the script... 
renamed to `editor image output.py` and saved in my external hdd, 
size=64 of the texture
name = texture
alpha = False
type Generated

**Comment by zeffii** [comment]
just name it `my_viewer_script`  (no .py needed)

**Comment by ly29** [comment]
@kalwalt 
That is strange, what error do you get?

**Comment by kalwalt** [comment]
still nothing, i will try later again.
@ly29 no error from terminal

**Comment by kalwalt** [comment]
Can you upload a blend file @ly29 ?

**Comment by ly29** [comment]
![imag2](https://cloud.githubusercontent.com/assets/6241382/23330265/28efb1f8-fb4a-11e6-9f5e-33e7d9d785c7.PNG)

@kalwalt 
[image_test.zip](https://github.com/Sverchok/Sverchok/files/801087/image_test.zip)
Slide the size of the grid and see how it updates

**Comment by ly29** [comment]
512x512 is still workable on my machine and feels snappy. 1024x1024 feel slow but is miracle compared to the old sverchok

**Comment by ly29** [comment]
@kalwalt 
Did it work?

**Comment by kalwalt** [comment]
i feel so sad:
![image_test_fail](https://cloud.githubusercontent.com/assets/1275858/23330314/0ee2607a-fb4b-11e6-87fa-9aea360439f6.png)
what happens today? there is solar storm?

from the console:

````
./blender
Read new prefs: /home/walter/.config/blender/2.78/config/userpref.blend
found bundled python: /home/walter/blender-2.78a-linux-glibc211-x86_64/2.78/python
archimesh: Imported multifiles
addon not found: 'sverchok'
measureit: Imported multifiles
version 3 imported

** Sverchok loaded with 203 nodes **
added keyboard items to Text Editor.
** version:  (0, 5, 9, 6)  **
** Have a nice day with sverchok  **

 ______ _    _ _______  ______ _______ _     _  _____  _     _
/______  \  /  |______ |_____/ |       |_____| |     | |____/
______/   \/   |______ |    \_ |_____  |     | |_____| |    \_
initialized.
Registered Code Autocomplete with 38 modules.
Registered Animation Nodes with 409 modules.
2017-02-25 11:06:21,168     INFO manuelbastionilab_logger Looking for an humanoid object...
2017-02-25 11:06:21,168     INFO manuelbastionilab_logger Blender version check passed...
2017-02-25 11:06:21,168     INFO manuelbastionilab_logger Object type passed...
2017-02-25 11:06:21,168     INFO manuelbastionilab_logger No existing valid human objects found in the scene
Time: 0.00008 - fps : 12345.68 - Function: update
Time: 0.00018 - fps : 5649.72 - Function: update
Time: 0.00050 - fps : 1988.07 - Function: updateEverything
Time: 0.00008 - fps : 12987.01 - Function: update
Time: 0.00032 - fps : 3105.59 - Function: updateEverything
read blend: /media/walter/packard-bell/documenti/blender/scripts/image_test.blend
2017-02-25 11:07:46,078     INFO manuelbastionilab_logger Looking for an humanoid object...
2017-02-25 11:07:46,079     INFO manuelbastionilab_logger Blender version check passed...
2017-02-25 11:07:46,079     INFO manuelbastionilab_logger Object type passed...
2017-02-25 11:07:46,080     INFO manuelbastionilab_logger No existing valid human objects found in the scene
Time: 0.00010 - fps : 9708.74 - Function: update
Time: 0.00006 - fps : 17241.38 - Function: update
Time: 0.00025 - fps : 3984.06 - Function: updateEverything
^CTraceback (most recent call last):
  File "/home/walter/blender-2.78a-linux-glibc211-x86_64/2.78/scripts/addons/sverchok-master/core/handlers.py", line 53, in sv_main_handler
    @persistent
KeyboardInterrupt

``

**Comment by zeffii** [comment]
`redux` is a separate addon. see the readme on the main page here.

**Comment by zeffii** [comment]
https://github.com/Sverchok/Sverchok/blob/master/README.md

**Comment by kalwalt** [comment]
i didn't understand this sorry

**Comment by zeffii** [comment]
youll see a new icon in your node tree options.

**Comment by ly29** [comment]
No problem, please test it. You will probably want to do your textures experiments using redux.

**Comment by kalwalt** [comment]
> No problem, please test it. You will probably want to do your textures experiments using redux.

exactly! i'm going to clone it

**Comment by ly29** [comment]
Both Redux and the old Sverchok can work at the same time, they are totally independent even if related so to speak.

**Comment by kalwalt** [comment]
i clone it in `addons` folder reanmed to `svrx` but the addons  is not loaded,

**Comment by ly29** [comment]
It does appear in settings under nodes?

**Comment by kalwalt** [comment]
@ly29 now i'm in it!
![image_test_ok](https://cloud.githubusercontent.com/assets/1275858/23330479/0d6705da-fb4f-11e6-81c1-114d5ac49dce.png)

**Comment by zeffii** [comment]
@kalwalt 
![image](https://cloud.githubusercontent.com/assets/619340/23330758/def2d028-fb56-11e6-857d-d413afab861e.png)

**Comment by ly29** [comment]
Hehe

What do you think of the speed difference?

**Comment by kalwalt** [comment]
> Hehe
 What do you think of the speed difference?

interesting!
i can say: ok for the redux! :+1:

**Comment by kalwalt** [comment]
@ly29 @zeffii i looked again into this: 

- to find if it possible a similar way for sverchok
- to find a way to save an animation

question: does it exist `array_as` function inside sverchok? in svrx is located in function.py, i don't find it in sverchok...

**Comment by zeffii** [comment]
`from svrx.util.function import array_as`  then inside sverchok.

**Comment by kalwalt** [comment]
> from svrx.util.function import array_as then inside sverchok.

ok i can do like this but will work only if you have svrx installed. i will think about it.

**Comment by ly29** [comment]
Copy the function over to Sverchok

**Comment by kalwalt** [comment]
@ly29 yes exactly what i did and it worked, see https://github.com/nortikin/sverchok/issues/1334 i hope soon to post more. Today spent my time on my first blender [addon](https://github.com/kalwalt/terragen_utils)
