### ISSUE TITLE
Mesh representation

### ISSUE THREAD

**Issue by ly29** [Sverchok/Sverchok#6]
To have two types ```SMesh``` and ```BMesh``` which are considered compatible and converted as needed by the system.
SMesh is an Sverchok representation of a mesh using flat ```numpy``` storage.

The two types would have the same socket representation but the mesh data would be converted as needed.  Perhaps also allow overload for certain functions and have two functions to avoid conversion.

To the user and the nodes this would basically be invisible, the intelligence would be in the base system

A partial sample implementation of a mesh using np storage 
https://github.com/nortikin/sverchok/blob/polygon_flat/utils/polygon.py

**Comment by zeffii** [comment]
i had hoped we would start storing data wrapped in dicts `{'kind of data':  data}` , becase when the data is set, it might as well pass that extra information along with it.. so it's a simple lookup in the sv_get..

**Comment by ly29** [comment]
So ```SvPolygon``` for flat storage of polygons. Backwards compatible to Sverchoks old format but new numpy storage which is similar to blenders loops.
