### ISSUE TITLE
OpenGL viwers

### ISSUE THREAD

**Issue by ly29** [Sverchok/Sverchok#62]
![openglviewer](https://cloud.githubusercontent.com/assets/6241382/23275418/c0722550-fa06-11e6-8ca1-ba94330f2bf3.PNG)
Did a quick test for drawing OpenGL with bmesh, went beyond expectation using the tessellated faces, then we only need to draw triangles.
All data is preprocessed in ```__call__``` and only what to draw, colors etc is passed on to callback.

Very rough state and cannot control drawing on/off for specific features.

Also need a new callback handler or a refactoring of the current one.

**Comment by ly29** [comment]
```python

def draw_bmesh(context, args):
    obj_list = args[0]
    face_list = args[1]
    col_list = args[2]
    edg_list = args[3]
    edge_col, vert_col = args[4]

    for verts, vert_index, colors, edges in zip(obj_list, face_list, col_list, edg_list):
        if vert_index:
            bgl.glBegin(bgl.GL_TRIANGLES)
            for idx in range(0, len(vert_index), 3):
                p0 = verts[vert_index[idx]]
                p1 = verts[vert_index[idx + 1]]
                p2 = verts[vert_index[idx + 2]]
                bgl.glColor3f(*colors[idx//3])
                bgl.glVertex3f(*p0)
                bgl.glVertex3f(*p1)
                bgl.glVertex3f(*p2)
            bgl.glEnd()
        if vert_col:
            bgl.glBegin(bgl.GL_POINTS)
            bgl.glColor3f(*vert_col)
            for vert in verts:
                bgl.glVertex3f(*vert)
            bgl.glEnd()
        if edge_col:
            bgl.glBegin(bgl.GL_LINES)
            bgl.glColor3f(*edge_col)
            for x, y in edges:
                bgl.glVertex3f(*verts[x])
                bgl.glVertex3f(*verts[y])
            bgl.glEnd()
```

**Comment by zeffii** [comment]
i think we can get away with this..

```
    def stop(self):
        bgl_callback.callback_disable(self.n_id, overlay='POST_PIXEL')
        if self.activate:
            bgl_callback.callback_enable(self.n_id, self.current_draw_data, overlay='POST_PIXEL')
```

**Comment by ly29** [comment]
Needs some more settings/bigger points size etc but usable now

**Comment by zeffii** [comment]
the bgl_callback must be renamed to `bgl_callback_3dview` then.

**Comment by ly29** [comment]
That would make sense.

**Comment by zeffii** [comment]
tho perhaps `bgl_callback.callback_disable`  should be able to figure out which was used to enable it in the first place. --- not essential for now.

**Comment by zeffii** [comment]
oh.. after looking carefully, the callback disable doesn't even care what kind overlay it is ..
```python
    def stop(self):
        bgl_callback.callback_disable(self.n_id)
        if self.activate:
            bgl_callback.callback_enable(self.n_id, self.current_draw_data, overlay='POST_PIXEL')
```

**Comment by zeffii** [comment]
and ` ^^^^^^^^^^^^^ ` is not that bad.

**Comment by ly29** [comment]
Yeah I noticed, made a ```bgl_callback_3dview``` with the overlay, when we merge we can switch over index viewer and removed the _2d file

**Comment by zeffii** [comment]
coolio.

**Comment by ly29** [comment]
![monkey3](https://cloud.githubusercontent.com/assets/6241382/23277493/4ee9622e-fa0e-11e6-80de-98b23bf59e7b.PNG)
Seems quite useful already, now all things are controllable.
- display list
- don't do heavy calcs in if not faces are needed

**Comment by ly29** [comment]
Won't have time for more today, will merge for tinkering.

**Comment by zeffii** [comment]
these are the peskier nodes :)

**Comment by ly29** [comment]
I copied a lot but by I spent less than on this than I did tracking down bugs for plane edges...

**Comment by ly29** [comment]
If you want tinker with point size or something bigger feel more than welcome.

**Comment by ly29** [comment]
The good thing about going via bmesh is that some verification has already been done for us.

**Comment by ly29** [comment]
I think I will make a quick hack and allow drawing of vertices, edges and faces via conversion to bm. 
Later we can make a more direct data path.

**Comment by ly29** [comment]
![viewrxgl](https://cloud.githubusercontent.com/assets/6241382/23294364/4aff3622-fa6b-11e6-8a48-3861aeb1cbbf.PNG)

Below complete new code for viewer node for rx data. I think this is asign that some abstractions are working out nicely.

```python
@stateful
class ViewNode(BMViewNode):
    bl_idname = "SvRxNodeRxViewGL"
    label = "Viewer Rx GL"

    def __call__(self,
                verts: Vertices = Required,
                edges: Edges = None,
                faces: Faces = None,
                mat: Matrix = None):
        bm = bmesh_from_pydata(verts[:,:3].tolist(), edges, faces)
        super().__call__(bm, mat)
```

**Comment by ly29** [comment]
These viewers should be considered a minimal level and could do with more advanced options, for example gatering colors from the bmesh, showing different materials per loop etc.

**Comment by ly29** [comment]
What is also nice that all fixes applied to the bmesh viewer will automatically work for the rx viewer

**Comment by ly29** [comment]
![error_draw](https://cloud.githubusercontent.com/assets/6241382/23294901/0ed8f23e-fa6e-11e6-93b0-c461c23ccddc.PNG)
Also get crashes with ```Error: EXCEPTION_ACCESS_VIOLATION```

**Comment by ly29** [comment]
So some extra paranoia to copy data from created bmesh since it probably deleted when falling out of scope but...

**Comment by ly29** [comment]
And it seems to be working 😃

**Comment by zeffii** [comment]
how expensive is a deepcopy of a bm, because the transforms are pretty rapid using `bmesh.ops.transform(  matrix ) `.

I wouldn't be surprised if  
```
bmnew = bmesh.ops.copy(bm)`
bmesh.ops.transform(bmnew, matrix)
```
is faster than iterating over a list of verts and transforming them.

**Comment by ly29** [comment]
Maybe yes. But I got strange results when I tried.

**Comment by zeffii** [comment]
i think we just can't `bm.clear() / .free()`

**Comment by zeffii** [comment]
and that happens automagically at the end of the viewers scope, i think.

**Comment by zeffii** [comment]
good to have the viewers again.

**Comment by ly29** [comment]
I made sure the data is copied now, for the bm case it was okay because the incoming bm is kept in the data tree cache

**Comment by ly29** [comment]
Some update stuff on this to be able to fix bugs and we could almost invite people in to try soonish.

**Comment by ly29** [comment]
![opstrans](https://cloud.githubusercontent.com/assets/6241382/23295709/5c585622-fa72-11e6-9377-9f7c210a38f6.PNG)

So this is what happens when I try with ```bmesh.ops.transform```

So updated to working below
```python
        if mat is not None:
            if self.node.use_ops_trans:
                bm = bm.copy()
                matrix = mu.Matrix(mat)
                bmesh.ops.transform(bm, matrix=matrix, verts=bm.verts)
                # was this not working
                # bmesh.ops.transform(bm, matrix=matrix)
                verts = [v.co[:] for v in bm.verts]
                bm.normal_update()
                normals = [f.normal[:] for f in bm.faces]
            else:
                matrix = mu.Matrix(mat)
                verts = [matrix * v.co for v in bm.verts]
                bm.normal_update()
                mat33 = matrix.to_3x3()
                normals = [(mat33 * f.normal)[:] for f in bm.faces]

```

**Comment by ly29** [comment]
Ahh, of course I have to specify the verts because not doing that means don't want to transform any...

**Comment by zeffii** [comment]
i am eager to see the speed difference :)

**Comment by ly29** [comment]
No totally coherent but leaning this way it seems.
Icosphere subdiv=5 and 3 matrices
```
SvRxNodeBMViewGL: GL View - ops.trans   0.079932    49.5%       
SvRxNodeBMViewGL: GL View mat*v         0.064907    40.2%   
```

**Comment by ly29** [comment]
Should make a way to run the timings 10 times or so and take minimums

**Comment by zeffii** [comment]
: /  can you tell what part of that 9 procent is the copy operation?

**Comment by ly29** [comment]
I could investigate but don't have more time right now

**Comment by ly29** [comment]
Sometimes the ops.transform is quicker.

**Comment by ly29** [comment]
So this is mostly usable, until there is time for taking it to the next level I think this does the job.

**Comment by ly29** [comment]
Of course the option for code path needs to be dumped
