### ISSUE TITLE
Types

### ISSUE THREAD

**Issue by ly29** [Sverchok/Sverchok#7]
The type system right now is as seen below. It is meant to provide metadata for the execution system and as basis for conversion between types. Dynamic typing is not allowed, however changing type based on setting in a node is allowed. A kind of generics is allowed.

Type | Socket class | data description
--------|-----------|----
Color  |  SvRxColorSocket | np.float64 shape=(N, 4) RGBA
TopoData  |  SvRxTopoSocket | Generic topological data
Edges  |  SvRxTopoSocket | np.uint, shape = (N, 2)
Faces  |  SvRxTopoSocket | SFaces class see #6 
SMesh  |  SvRxMeshSocket | SMesh see #6 
BMesh | SvRxMeshSocket | Bmesh
Object  |  SvRxObjectSocket | Blender obj reference
Number  |  SvRxFloatSocket | Generic number
Matrix  |  SvRxMatrixSocket | np 4x4 Matrix 
Anytype  |  SvRxAnySocket | Generic type
String  |  SvRxStringSocket | str
Int  |  SvRxIntSocket | np.int shape = (N,)
Float  |  SvRxFloatSocket | np.float64 shape = (N,) 
Vector  |  SvRxVectorSocket | np.float64 shape=(N,4), used for when you want a vector
Vertices  |  SvRxVertexSocket | np.float64 shape=(N,4)

**Comment by ly29** [comment]
Of course this is just a rough draft

**Comment by portnov** [comment]
What do you mean by TopoData? Is it just a tuple of (vertices, edges, faces) like in current sverchok, or?...

**Comment by ly29** [comment]
A virtual(?) type when both edge data or faces data could be accepted.

```python
class TopoData(SvBaseType):
     pass

class Faces(TopoData):

class Edges(TopoData):

```

Edges and Faces are then in turn represented using np.array, dtype=np.uint

**Comment by portnov** [comment]
Ah, so it's something like "edg/pol" socket that some nodes have in current sverchok. Ok.

**Comment by ly29** [comment]
Yes, exactly.

**Comment by ly29** [comment]
Also the idea is to start using the type data in an intelligent fashion.

**Comment by nortikin** [comment]
why not use topo data instead of faces+edges. less sockets more clear

**Comment by ly29** [comment]
The main reason is that faces and edges are fundamentally different. It will be quite easy to remove that if feels unnecessary but more work to add it afterwards.
And also note that they are the same socket, but different types.

**Comment by portnov** [comment]
Probably we will have to add switch with two positions (into each node): 1) use separate verts/edges/faces sockets; 2) use one mesh socket. Conversion between representations better be handled by engine.

**Comment by ly29** [comment]
So having played around and tested this it out a bit, it is time to re think slightly. Also some renaming to avoid name clashes would probably be clever.

**Comment by ly29** [comment]
So the ```generator``` decorator solved this problem in a fine way.

Will turn this into a doc on wiki, closing since it is slightly outdated.

**Comment by nortikin** [comment]
vector is originally two points, start and finish, as (1,2,3)(4,5,6) form.
Vertex can become point as (1,2,3)
maybe N4 not needed in vector and point (lets call it as point to avoid misunderstanding Vector-Vertex)

**Comment by ly29** [comment]
or we just use 4 everywhere internally?
